define({
    //#region Rota infrastructure resources
    rota: {
        bimar: "Bimar Information Technology 2016",
        username: 'User Name',
        password: 'Password',
        invalid_grant: 'Failed to login, please check your credentials',
        kategoriler: 'Categories',
        cachetemizle: 'Clear Cache',
        dildegistir: 'Switch Language',
        tamam: 'OK',
        onay: 'Confirm',
        iptal: 'Cancel',
        yenile: 'Refresh',
        arama: 'Search...',
        paylasimdahata: 'Error in sharing...{0}',
        lutfenbekleyiniz: 'Please Wait..',
        dilsecimiyapiniz: 'Please choose language',
        dildegisimonay: 'Are you sure to change the current language ?',
        dildegisimtamamlandi: 'Current language has been set to {0}',
        zatensecilidilaktif: 'Current language already set to {0}',
        ayarlar: 'Settings',
        cachesilmeonay: "Are you sure to clear the cache ?",
        cachetemizlendi: 'Cache is clear now !',
        login: 'Login',
        giris: 'Log in',
        degergirin: 'Fill in input...',
        detay: 'Detail',
        kopyala: 'Copy to clipboard',
        paylas: 'Share',
        whatsapppaylas: 'Share via WhatsApp',
        kopyalandi: 'Copied',
        basariylapaylastiniz: 'Shared',
        yukleniyor: 'Please wait...',
        kullanicipasswordgiriniz: 'Provide username and password !',
        iletisim: 'Contact us',
        cikis: 'Sign out',
        kapat: 'Quit',
        cikisonay: 'Are you sure to log off ?',
        geri: 'Back',
        offline: 'Network connection failed !',
        hata: 'Error',
        yenidenbaslat: 'Restart !',
        hataolustu: 'An error occured !',
        hataozur: 'Apologize for inconvenience situation. We have been informed about the exception.We will fix it soon.',
        hataaciklama: 'Error description :',
        mailfromzorunlu: 'From field is missing',
        mailtozorunlu: 'TO field is missing',
        mailgonderimindehata: 'Mail sending is failed',
        mailbodyzorunlu: 'Body is missing !',
        introyugec: 'Skip Intro',
        sonraki: 'Next',
        onceki: 'Previous',
        kullanmayabasla: 'Start using app',
        intro: 'Intro',
        uygdurduruldu: 'App is disabled temporarly due to some specific reason. You will be notified about this issue as soon as posible',
        verhatali: 'New version found (ver : {0}). Please always use the latest version',
        hakkimizda:'About us',
        kayitol: "Kayıt Ol",
        girisyap: "Giriş Yap",
        facebook: "Facebook ile giriş yap"
    },
    //#endregion

    //#region Ynl resources
    air: {
        refresh: 'Refresh',
        flightlist: 'Flight List',
        flightcabinlist: 'Flight Cabin List',
        send: 'Send',
        name: 'Your Name',
        subject: 'Subject',
        message: 'Message',
        contact: 'Contact Form',
        email: 'E-mail',
        emailSuccess: 'Your message is successfully sent ',
        aboutUs: 'About Us',
        intro: 'Welcome to ArkasAir Application',
        approve: 'Approve',
        decline: 'Decline',
        flightLegs: 'Flight Legs',
        takeOff: 'TakeOff',
        landing: 'Landing',
        flightfilter: 'Flight Search',
        aircraft: 'Aircraft',
        search: 'Search',
        searchCriteria: 'Search Criteria',
        status: 'Status',
        planned: 'Planned',
        actual: 'Actual',
        scheduled: 'Scheduled',
        hasWarning: 'Has Warning',
        yes: 'Yes',
        no: 'No',
        warnings: 'Warnings',
        edit: 'Edit',
        remove: 'Delete',
        save: 'Save',
        legDetail: 'Leg Details',
        flightType: 'Flight Type',
        airportFrom: 'Dep. Airport',
        airportTo: 'Arv. Airport',
        takeOff: 'Take Off',
        landing: 'Landing',
        pilotFlying: 'Pl. Flying',
        pilotNonFlying: 'Pl. Non-flying',
        pilotAdditional: 'Pl. Additional',
        flightAttendant: 'Flight Attendant',
        startDate: 'Start Date',
        finishDate: 'Finish Date',
        longRange: 'Long Range',
        arrivalAirport: 'Arrival Airport',
        departureAirport: 'Departure Airport',
        flightNo: 'Flight No',
        dcRest: 'Dc Rest',
        dcFdt: 'Dc Fdt',
        flightPlan: 'Flight Plan',
        back: 'Back',
        addLeg: 'Add Leg',
        leadPax: 'Lead Pax',
        client: 'Client',
        checkIn: 'Check In',
        checkOut: 'Check Out',
        paxNumber: 'Pax No',
        preparationTime: 'Preparation Time',
        arkasairMobile: 'ArkasAir Mobile',
        remainingDays: "Remaining Days",
        searchFlights: "Search Flights",
        listFlights: "List Flights",
        createFlight: "Create Flight",
        cancel: "Cancel"
    }
    //#endregion
});